- blackbox-test/src/main/java/org/example/customer/raw/WithRawContent.java
- blackbox-test/src/test/java/org/example/customer/raw/WithRawContentTest.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/PropertyIgnoreReader.java
- jsonb-jackson/src/main/java/io/avaje/jsonb/jackson/JacksonReader.java
- jsonb-jackson/src/main/java/io/avaje/jsonb/jackson/JacksonWriter.java
- jsonb-jakarta/src/main/java/io/avaje/jsonb/jakarta/JakartaJsonReader.java
- jsonb-jakarta/src/main/java/io/avaje/jsonb/jakarta/JakartaJsonWriter.java
- jsonb/src/main/java/io/avaje/jsonb/Json.java
- jsonb/src/main/java/io/avaje/jsonb/JsonReader.java
- jsonb/src/main/java/io/avaje/jsonb/JsonWriter.java
- jsonb/src/main/java/io/avaje/jsonb/Jsonb.java
- jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java
- jsonb/src/main/java/io/avaje/jsonb/core/ObjectJsonReader.java
- jsonb/src/main/java/io/avaje/jsonb/core/RawAdapter.java
- jsonb/src/main/java/io/avaje/jsonb/spi/DelegateJsonWriter.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JGenerator.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JParser.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JsonGenerator.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JsonParser.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JsonReadAdapter.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JsonWriteAdapter.java
- jsonb/src/test/java/io/avaje/jsonb/stream/JParserTest.java
Note that this allows for both read and write of raw json content, where Jackson @JsonRawValue is only for write
> Add @Json.Raw support (similar to Jackson @JsonRawValue)

- README.md
it's kinda tedious to constantly update the version for every release
> Remove explicit version from README

- README.md
> Update Docs Link

- README.md
Occasionally I get asked about the default types jsonb supports
> Adds Built in Types to README

- jsonb/pom.xml
- jsonb/src/main/java/io/avaje/jsonb/spi/DefaultJsonbProvider.java
> Use avaje-inject 8.13-RC2 plugin using Supplier to support both javax and jakarta

- jsonb-generator/pom.xml
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/GenericTypeParser.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/PropertyIgnoreReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- use the new isPresentMethod on the prisms.
- replace that one Stack with a Deque
Kinda relies on 1.4 being deployed
> Use Prisms 1.4

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/MethodReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleAdapterWriter.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleComponentWriter.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
perhaps static is the way to go?
> Static Processor Context

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/AdapterName.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/package-info.java
- jsonb/src/main/java/io/avaje/jsonb/core/CollectionAdapter.java
- jsonb/src/main/java/io/avaje/jsonb/core/Util.java
- jsonb/src/main/java/io/avaje/jsonb/spi/DefaultJsonbProvider.java
- jsonb/src/main/java/io/avaje/jsonb/stream/Base64.java
- jsonb/src/main/java/io/avaje/jsonb/stream/WriterOutputStream.java
- Merge nested if statements
- use {} instead of new `byte[0]`
- guard string comparisons against null
- remove unused imports
> Sonar Fixes

- jsonb-jackson/pom.xml
- jsonb/pom.xml
It should only be used with jsonb-jackson
> Remove Jackson Core from Jsonb

- blackbox-test/src/main/java/org/example/customer/subtype/Bocchi.java
- blackbox-test/src/main/java/org/example/customer/subtype/Car.java
- blackbox-test/src/main/java/org/example/customer/subtype/Dwayne.java
- blackbox-test/src/main/java/org/example/customer/subtype/TheRock.java
- blackbox-test/src/test/java/org/example/customer/subtype/TheRockTest.java
- jsonb-generator/pom.xml
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/MethodReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
Before was throwing errors and the only way to get it to work was by adding a dummy setter.
> Support Protected Constructors with SubType

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
> Use ThreadLocal ProcessorContext

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/EnumReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
> #82 follow up - Format code, Add types to error message, Fields to local variables, Add comments to empty methods

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Append.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeMeta.java
- Use ProcessingContext.sourceVersion()
- Change to use a single ThreadLocal
> Use ProcessingContext.sourceVersion() for code gen features

- .github/workflows/build.yml
- jsonb-jackson/src/main/java/io/avaje/jsonb/jackson/JacksonAdapter.java
- jsonb/pom.xml
- jsonb/src/main/java/io/avaje/jsonb/JsonView.java
- jsonb/src/main/java/io/avaje/jsonb/Jsonb.java
- jsonb/src/main/java/io/avaje/jsonb/core/DJsonType.java
- jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java
- jsonb/src/main/java/io/avaje/jsonb/core/ViewBuilder.java
- jsonb/src/main/java/io/avaje/jsonb/spi/JsonStreamAdapter.java
- jsonb/src/main/java/io/avaje/jsonb/stream/DJsonOutput.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JGenerator.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JsonOutput.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JsonStream.java
- jsonb/src/main/java/io/avaje/jsonb/stream/NimaJsonOutput.java
- jsonb/src/main/java/io/avaje/jsonb/stream/Recycle.java
- jsonb/src/main/java/module-info.java
- jsonb/src/test/java/io/avaje/jsonb/stream/JsonWriterTest.java
For Nima its used like:
```java
// given response is a Nima Http ServerResponse
jsonType.toJson(result, JsonOutput.of(response));
```
> Add JsonOutput to optimise writing to Nima ServerResponse

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeMeta.java
Some method signatures have got big in terms of number of parameters so I'll look to follow up with some refactoring to fix that
> Format and remove some unused

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/NamingConventionReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeReader.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/Packet.java
- jsonb/src/main/java/io/avaje/jsonb/Json.java
- Modifies the Import annotation to allow importing polymorphic types.
- now can set the case insensitivity and naming convention of imported types
Fixes #112
> Import Subtypes

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/NamingConventionReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeReader.java
- Rename getImportedJson() -> importedJson()
- Rename getImportedSubtypes() -> importedSubtypes()
- Simplify previewEnabled ...
- Some format changes
> No effective change - format and rename internal methods

- jsonb/src/main/java/io/avaje/jsonb/spi/Bootstrap.java
> Update Bootstrap Javadoc

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java
Now can fully handle all annotation situations
> Update Trim Annotations logic

- README.md
- blackbox-test/src/main/java/org/example/customer/subtype/MoveAccuracy.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/MoveAccuracy.java
> Always have a string adapter for subtypes

- blackbox-test/src/main/java/org/example/customer/enums/EnumExample.java
- blackbox-test/src/test/java/org/example/customer/enums/EnumExampleTest.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
- jsonb/src/main/java/io/avaje/jsonb/core/CoreAdapterBuilder.java
- jsonb/src/main/java/io/avaje/jsonb/core/EnumMapAdapter.java
- jsonb/src/main/java/io/avaje/jsonb/core/MapAdapter.java
- jsonb/src/main/java/io/avaje/jsonb/core/Util.java
Adds an Adapter for Serializing Enum Maps.
fixes #131
> Add support for Enum Key serialization

- blackbox-test/src/main/java/org/example/customer/PrettyExample.java
- blackbox-test/src/test/java/org/example/customer/BasicPubFieldsTest.java
- blackbox-test/src/test/java/org/example/customer/CustomerTest.java
- blackbox-test/src/test/java/org/example/customer/PrettyTest.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JGenerator.java
> Fix Pretty JSON

- blackbox-test/src/test/java/org/example/customer/BasicPubFieldsTest.java
- blackbox-test/src/test/java/org/example/customer/CustomerTest.java
- blackbox-test/src/test/java/org/example/customer/PrettyTest.java
- jsonb/src/main/java/io/avaje/jsonb/stream/JGenerator.java
This puts it back to what it was.
> Put pretty json indentation back to 2 spaces

- blackbox-test/src/main/java/org/example/customer/iface/AIFace.java
- blackbox-test/src/main/java/org/example/customer/iface/BIFace.java
- blackbox-test/src/main/java/org/example/customer/iface/CIFace.java
- blackbox-test/src/main/java/org/example/customer/iface/package-info.java
- blackbox-test/src/test/java/org/example/customer/iface/AIFaceTest.java
- blackbox-test/src/test/java/org/example/customer/iface/BIFaceTest.java
- blackbox-test/src/test/java/org/example/customer/iface/CIFaceTest.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldProperty.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/MethodProperty.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/MethodReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
These support toJson() but not fromJson()
> Support @Json on interfaces and abstract types

- blackbox-test/src/main/java/org/example/customer/alias/WithAlias.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/package-info.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/UtilTest.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/TestClass.java
- jsonb/src/main/java/io/avaje/jsonb/Json.java
To be more consistent with the other json annotations
> Rename @Json.JsonAlias -> @Json.Alias with deprecation

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-spring-adapter/pom.xml
Import errors will show the exact element that failed
> Slightly Improve Logging

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java
will throw a compile exception if missing required constructor/factory
> More Logging for Custom Adapter Errors

- blackbox-test/src/main/java/module-info.java
- jsonb-generator/pom.xml
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentMetaData.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleComponentWriter.java
- jsonb-generator/src/main/resources/META-INF/services/javax.annotation.processing.Processor
- jsonb-jackson/pom.xml
- jsonb/src/main/java/io/avaje/jsonb/JsonReader.java
Now will fail compilation if somebody forgets to add the provides clause for `Jsonb.GeneratedComponent`
> Validate module-info provides

- blackbox-test/pom.xml
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-inject-plugin/pom.xml
> Warn when jsonb plugin is not detected in module-info

- .github/workflows/build.yml
- jsonb-generator/pom.xml
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/GenericType.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleAdapterWriter.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleComponentWriter.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java
- jsonb/pom.xml
- jsonb/src/main/java/io/avaje/jsonb/Json.java
you get the idea by now, use prisms 1.14
> Prisms 1.14

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/EnumReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java
now import strings will be cleaned of any extra non-valid characters
> Sanitize imports

- jsonb/pom.xml
- jsonb/src/main/java/io/avaje/jsonb/stream/NimaJsonOutput.java
> Helidon-RC1

- jsonb-generator/pom.xml
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java
- jsonb/src/main/java/io/avaje/jsonb/stream/BufferRecycleStrategy.java
Uses Prisms 1.17 to check the module path for the `io.avaje.jsonb.plugin` module
> Check modulePath for plugin

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
you get the idea, disables module validation if the plugin is detected
> Support the Avaje Build Plugin

- .github/workflows/build.yml
- .github/workflows/jdk-ea.yml
It's pretty nice to know immediately when stuff is failing
> Run EA builds on PRs

- .github/workflows/build.yml
- .github/workflows/jdk-ea-stable.yml
- .github/workflows/jdk-ea.yml
> Adds EA stable workflow

- .github/workflows/build.yml
- pom.xml
configures build to be [reproducible](https://maven.apache.org/guides/mini/guide-reproducible-builds.html)
> Reproducible Build

- jsonb-generator/pom.xml
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/MultiConstruct.java
> Improve Constructor Detection

- jsonb-inject-plugin/pom.xml
- jsonb-inject-plugin/src/main/java/io/avaje/jsonb/inject/DefaultJsonbProvider.java
As BufferRecycleStrategy is now in avaje-json-core
> Fix the inject-plugin due to move of BufferRecycleStrategy

- blackbox-test/src/main/java/org/example/customer/node/HelloWithUnmapped.java
- blackbox-test/src/test/java/org/example/customer/node/HelloWithUnmappedTest.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldProperty.java
So Unmapped type can either be a Map<String,Object> or a JsonObject.
> [jsonb] JsonB support use of JsonObject for @Json.Unmapped type

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/JsonbProcessor.java
> Cancel generation if a previous apt round fails

- jsonb/src/main/java/io/avaje/jsonb/core/BasicTypeAdapters.java
> Remove adapters from jsonb that were moved to json-core (as they are now unused)

- blackbox-test/src/main/java/module-info.java
- blackbox-test/src/main/java/org/example/pkg_private/PackagePrivate.java
- blackbox-test/src/main/java/org/example/pkg_private/PackagePrivateCreator.java
- blackbox-test/src/test/java/org/example/pkg_private/PackagePrivateCreatorTest.java
- blackbox-test/src/test/java/org/example/pkg_private/PackagePrivateTest.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/AdapterName.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentMetaData.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/JsonbProcessor.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleAdapterWriter.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleComponentWriter.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ValueReader.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/pkg_private/PackagePrivate.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/pkg_private/PackagePrivateCreator.java
This change makes the generator create separate JsonComponents for package-private client classes.
> Fully Support pkg-private json adapters

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java
properly read all the meta annotations
> Properly read all the meta annotations for package private components

- blackbox-test/pom.xml
- json-core/pom.xml
- json-node/pom.xml
- jsonb-bom/pom.xml
- jsonb-generator/pom.xml
- jsonb-inject-plugin/pom.xml
- jsonb-jackson/pom.xml
- jsonb-spring-adapter/pom.xml
- jsonb/pom.xml
- pom.xml
> bump version

- jsonb/src/main/java/io/avaje/jsonb/Jsonb.java
- jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java
- jsonb/src/main/java/io/avaje/jsonb/core/ExtensionLoader.java
Now can load `JsonComponent`s in all sorts of wacky situations
> Support Custom Classloader

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldProperty.java
- jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/GenericCascade.java
> Fix cascading generic types

- jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleAdapterWriter.java
How the class (de)serializes seems a little more pertinent
> Move view methods below to/from json methods
