avaje/avaje-jsonb

.gitignore, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
Given this class
```
@Json
@Valid
public class GetBeanForm {
@NotNull
@Size(min = 2, max = 150)
private String name;
@Email
@Size(max = 100)
private String email;
... getters/setters
}
```
the field types are currently read as:
```
java.lang.@javax.validation.constraints.NotNull,@javax.validation.constraints.Size(min=2, max=150) String
java.lang.@javax.validation.constraints.Email,@javax.validation.constraints.Size(max=100) String
```
This PR fixes that.
=> Fix Annotated Fields

.gitignore, blackbox-test/pom.xml, jsonb/src/main/java/io/avaje/jsonb/stream/JsonStream.java, jsonb/src/main/java/io/avaje/jsonb/stream/Recycle.java
Benched using https://github.com/fabienrenaud/java-json-benchmark
Here are the current benchmarks with no changes
Benchmarks without ThreadLocal and using JVM Recycle 
part of #37
=> Use JVM 19 Buffer Recycling

jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java
The following fails to compile.
```
@Json
@Getter
@Setter
public class Person() {
@Ignore
private   String s;
private   Instant time;
private   int num;
}
```
It seems the adapter for the ignored String field is still getting added in the generated constructor, but not the fields.
```
// naming convention Match
// s [java.lang.String] name:s ignoreSerialize ignoreDeserialize
// time [java.time.Instant] name:time constructor
// sgsgs [int] name:sgsgs constructor
private final JsonAdapter<Instant> instantJsonAdapter;
private final JsonAdapter<Integer> pintJsonAdapter;
private final PropertyNames names;
public HelloController$PersonJsonAdapter(Jsonb jsonb) {
this.stringJsonAdapter = jsonb.adapter(String.class);
this.instantJsonAdapter = jsonb.adapter(Instant.class);
this.pintJsonAdapter = …
```
=> Now @Ignore works when both serialize and deserialize are false

blackbox-test/src/main/java/org/example/customer/IErrOnRead.java, blackbox-test/src/test/java/org/example/customer/IErrOnReadTest.java, jsonb-jackson/src/main/java/io/avaje/jsonb/jackson/JacksonWriter.java, jsonb/src/main/java/io/avaje/jsonb/JsonWriter.java, jsonb/src/main/java/io/avaje/jsonb/core/DJsonType.java, jsonb/src/main/java/io/avaje/jsonb/spi/DelegateJsonWriter.java, jsonb/src/main/java/io/avaje/jsonb/stream/JGenerator.java, jsonb/src/main/java/io/avaje/jsonb/stream/JsonGenerator.java, jsonb/src/main/java/io/avaje/jsonb/stream/JsonWriteAdapter.java, jsonb/src/test/java/io/avaje/jsonb/stream/DieselAdapterTest.java
- Adds markIncomplete() to indicate when an error has occurred during serialisation
- When not complete then do not flush to the underlying outputStream (so that it can be reset for sending error content)
=> Fix to JsonWriter to not flush underlying outputStream when error during serialisation

jsonb-generator/src/main/java/io/avaje/jsonb/generator/AliasReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/TestClass.java, jsonb/src/main/java/io/avaje/jsonb/Json.java
Adds a new annotation we can use to specify alternate deserialization names.
```
@Json
@Getter
@Setter
public class TestClass {
@Json.JsonAlias({"something", "something2"})
private String alias;
private String s;
private int i;
private Integer integer;
private char ch;
private Character chara;
private List<String> list;
}
```
generated adapter fromJson looks like.
```
@Override
public TestClass fromJson(JsonReader reader) {
TestClass _$testClass = new TestClass();
// read json
reader.beginObject();
reader.names(names);
while (reader.hasNextField()) {
String fieldName = reader.nextField();
switch (fieldName) {
case "something":
case "something2":
case "alias": {
_$testClass.setAlias(stringJsonAdapter.fromJson(reader)); break;
}
case "s": { …
```
=> Add Json Alias annotation

jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleComponentWriter.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java
Change generation to use expanded short name (to avoid name conflicts when inner types have the same name)
```
public class AuthProvider  {
@Json
public record Oauth2Token(
@Property("expires_in") int expiresIn,
@Property("access_token") String value,
@Property("token_type") String tokenType) {}
}
```
now in the GeneratedJsonComponent class, will generate like this
```
builder.add(AuthProvider.Oauth2Token.class, AuthProvider$Oauth2TokenJsonAdapter::new);
```
=> Lengthen Inner Type short names 

.github/workflows/build.yml, jsonb-generator/pom.xml, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeMeta.java
- use 1.3 of prisms
- `TypeSubTypeMeta`'s `name` field actually can't be null anymore, so changed the condition to use isBlank
=> Use Avaje Prisms 1.3

jsonb-generator/pom.xml
It seems the http generators can't detect jsonb on the CP while using the mvn compiler plugin.
=> Jsonb is no longer optional dependency for generators

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java
With prisms, there is no ".class" suffix to trim off, so it was butchering the Class Names instead.  Fixes #60
=> Fix MetaData Reading

jsonb/pom.xml
The prior compiled using jakarta.inject.Provider rather than Supplier. We want to use Supplier to be compatible with the javax.inject of avaje-inject.
=> Fix avaje-inject plugin to be compatible with 8.13-RC4 (Supplier)

jsonb/src/main/java/io/avaje/jsonb/stream/Recycle.java
It's the darndest thing, I'm upgrading the Json Java benchmark and it looks like the JVM recycling drastically reduces performance. When I take that out it's back to its normal speedy self. I say we revert the recycling for now and revisit when JDK 20 comes out.
=> Revert JVM Recycling

blackbox-test/src/main/java/org/example/customer/enums/Staff.java, blackbox-test/src/main/java/org/example/customer/enums/StaffStatus.java, blackbox-test/src/test/java/org/example/customer/enums/StaffStatusTest.java, jsonb-generator/pom.xml, jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeMeta.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java, jsonb/src/main/java/io/avaje/jsonb/core/BasicTypeAdapters.java
I remembered `EnumMap` was a thing, so used that to fix the issue. Fixes #77 
- converts `toValue` to use EnumMap instead of HashMap to get enum value. 
- converts `toValue` to be a `Map<Object, T>` to get enum type
- support long, double, and boolean enum value.
- on JDK17, use `instanceof` pattern matching for subtype
- use short names for subtype
=> Fix Null Enum Bug/SubType Short Name

blackbox-test/src/main/java/org/example/customer/subtype/Animal.java, blackbox-test/src/main/java/org/example/customer/subtype/Cat.java, blackbox-test/src/test/java/org/example/JsonIgnoreTest.java, blackbox-test/src/test/java/org/example/customer/CustomerTest.java, blackbox-test/src/test/java/org/example/customer/SomeAddressWrapperTest.java, blackbox-test/src/test/java/org/example/customer/cascade/MCTopTest.java, blackbox-test/src/test/java/org/example/customer/subtype/AnimalTest.java, blackbox-test/src/test/java/org/example/customer/views/ViewTest.java, blackbox-test/src/test/java/org/example/other/place/MyOtherClassTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/BeanReader.java, jsonb-jackson/src/test/java/org/example/CustomerTest.java, jsonb/src/main/java/io/avaje/jsonb/Jsonb.java, jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java
empty != null, so I can't really think of a situation where you wouldn't want to serialize an empty array. People have been tripped up by this and I expect this to become a recurring question. Why not just make it an opt-in feature
I also know a guy that uses an enum as his type property, he kinda needs this fast.`toString` works for now, but will add a proper enum switch logic later.
- serialize empty collections by default
-  fix bug where property names were missing a comma
- now if you define an enum type property it will be used in the `fromJson` subtype switch
=> Serialize empty Collections by default/Use Enum TypeProperty for SubTypes (Part 1)

README.md, jsonb/src/main/java/io/avaje/jsonb/core/JavaTimeAdapters.java
People really shouldn't be using it, but the reality is that this is still being used all over the place. Will serialize/deserialize as ISO timestamp.
=> Add Default `java.util.Date` Adapter

README.md, jsonb-spring-adapter/pom.xml, jsonb-spring-adapter/src/main/java/io/avaje/jsonb/spring/JsonBAutoConfiguration.java, jsonb-spring-adapter/src/main/java/io/avaje/jsonb/spring/JsonbHttpConverterAutoConfiguration.java, jsonb-spring-adapter/src/main/java/io/avaje/jsonb/spring/JsonbHttpMessageConverter.java, jsonb-spring-adapter/src/main/java/io/avaje/jsonb/spring/JsonbMVCAutoConfiguration.java, jsonb-spring-adapter/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, pom.xml
Reflection heavy though it is, you cannot deny that spring is one of the most popular frameworks of all time. This PR adds a module that autoconfigures spring to serialize/deserialize JSON HTTP messages with avaje jsonb. 
tested with https://github.com/spring-guides/gs-spring-boot/tree/main/complete
Didn't do Webflux because I expect reactive APIs to eventually become even more uncommon with the advent of Loom
=> Add Spring Starter

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
Apparently, JDK 13 added an `isPreviewEnabled` method. So we can reflect it to see if previews are enabled.
=> Now can generate with preview features

jsonb-generator/pom.xml, jsonb-inject-plugin/pom.xml, jsonb-inject-plugin/src/main/java/io/avaje/jsonb/inject/DefaultJsonbProvider.java, jsonb-inject-plugin/src/main/java/module-info.java, jsonb-inject-plugin/src/main/resources/META-INF/services/io.avaje.inject.spi.Plugin, jsonb/pom.xml, jsonb/src/main/java/module-info.java, jsonb/src/main/resources/META-INF/services/io.avaje.inject.spi.Plugin, pom.xml
It seems we won't see multi-module jars for a couple of years. This was the recommended way the JDK devs said to do it.
Fixes #99 (this'll work on both the CP and module path)
=> Fix Hard Inject Dependency (cyclical plugin dependency)

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/MethodReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeMeta.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/Example2Packet.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/Example3Packet.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/ExamplePacket.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/Packet.java
This fixes the wrong adapters being used for `toJson` and `fromJson `
fixes https://github.com/avaje/avaje-jsonb/issues/102
=> Fix Subtype `toJson` for subtypes having same field name with different types.

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java
IntelliJ is telling me that .filter(Objects::nonNull) is always true. The prior .map() is returning an Optional that is never null, so we should be able to remove this .filter() here.
=> IntelliJ - The .filter(Objects::nonNull) is always true

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/SubTypeRequest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeSubTypeMeta.java
Refactoring to reduce method arguments passed around, by introducing SubTypeRequest. Also means we can hide the frequency and common name maps to be internal to SubTypeRequest
=> Refactor generator TypeSubTypeMeta to use SubTypeRequest

blackbox-test/src/main/java/org/example/customer/ErrorResponse.java, blackbox-test/src/main/java/org/example/customer/customtype/CustomTypeComponent.java, blackbox-test/src/test/java/org/example/customer/customtype/CustomScalarTypeTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleAdapterWriter.java, jsonb-jackson/src/test/java/org/example/AddressJsonAdapter.java, jsonb-jackson/src/test/java/org/example/ContactJsonAdapter.java, jsonb-jackson/src/test/java/org/example/CustomerJsonAdapter.java, jsonb-jackson/src/test/java/org/example/MyBasicJsonAdapter.java, jsonb-jackson/src/test/java/org/example/MyEnumJsonAdapter.java, jsonb-jackson/src/test/java/org/example/MyIntEnumJsonAdapter.java, jsonb/src/main/java/io/avaje/jsonb/JsonAdapter.java, jsonb/src/main/java/io/avaje/jsonb/NullSafeAdapter.java, jsonb/src/main/java/io/avaje/jsonb/core/ArrayAdapter.java, jsonb/src/main/java/io/avaje/jsonb/core/BasicTypeAdapters.java, jsonb/src/main/java/io/avaje/jsonb/core/CollectionAdapter.java, jsonb/src/main/java/io/avaje/jsonb/core/CoreAdapterBuilder.java, jsonb/src/main/java/io/avaje/jsonb/core/MapAdapter.java, jsonb/src/main/java/io/avaje/jsonb/core/MathAdapters.java, jsonb/src/main/java/io/avaje/jsonb/core/RawAdapter.java, jsonb/src/main/java/io/avaje/jsonb/core/StreamAdapter.java
It occurs to me that JsonAdapter doesn't need to be an abstract class. Maybe we should put this in 2.0 since anybody creating their own custom adapters(but why??) would get a compilation error.
=> Make JsonAdapter an Interface

jsonb-generator/pom.xml, jsonb-generator/src/main/java/io/avaje/jsonb/generator/GenericType.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/ProcessorTest.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/ArrayListCollection.java
Now we can do something like this. 
```
@Json
public class ArrayListCollection {
private ArrayList<String> list;
public ArrayList<String> getList() {
return list;
}
public void setList(ArrayList<String> list) {
this.list = list;
}
}
```
(I personally would never do this, but some libs generate classes that use an impl directly).
- now will not fail compilation when JSON is placed on an abstract type.
- will check a types interfaces to see if it implements list/set/stream.
=> Now can use List/Set/Stream impls directly

jsonb-inject-plugin/src/main/java/module-info.java
now can just add `requires io.avaje.jsonb.plugin` and have the jsonb module resolved.
=> transitive plugin dependencies

jsonb-generator/pom.xml
Since avaje http no longer uses Class.forName to detect Jsonb, we can make this optional.
=> Make generator's jsonb optional

jsonb/src/main/java/io/avaje/jsonb/JsonReader.java, jsonb/src/main/java/io/avaje/jsonb/core/StreamAdapter.java, jsonb/src/main/java/io/avaje/jsonb/stream/JParser.java, jsonb/src/main/java/io/avaje/jsonb/stream/JsonParser.java, jsonb/src/main/java/io/avaje/jsonb/stream/JsonReadAdapter.java, jsonb/src/test/java/io/avaje/jsonb/stream/ArrayTest.java, jsonb/src/test/java/io/avaje/jsonb/stream/StreamTest.java
Adds hasNextStreamElement() which will be used for x-json-stream and thus the hasNextElement() is tightened up to expect the comma or ] and throws a parsing exception when that isn't the case.
=> #138 Missing commas between array elements is allowed when parsing exception is expected

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java
Fix in ComponentReader to use addFactory() when reading back @MetaData.Factory types
=> Fix partial compile with component Factory (used for generic types)

blackbox-test/src/main/java/org/example/customer/iface/DIFace.java, blackbox-test/src/main/java/org/example/customer/iface/EIFace.java, blackbox-test/src/main/java/org/example/customer/iface/implementation/MyDIFace.java, blackbox-test/src/test/java/org/example/customer/iface/BIFaceTest.java, blackbox-test/src/test/java/org/example/customer/iface/CIFaceTest.java, blackbox-test/src/test/java/org/example/customer/iface/DIFaceTest.java, blackbox-test/src/test/java/org/example/customer/iface/EIFaceTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Constants.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/package-info.java, jsonb/src/main/java/io/avaje/jsonb/Json.java
- Fixes a bug where Json.Import.List was not being read
- Adds support for Interface type fromJson() by specifying an implementation
e.g. `implementation = MyDIFace.class` - to support `fromJson()` for interface type
```java
@Json.Import(value = DIFace.class, implementation = MyDIFace.class)
public record MyDIFace(String one, long two) implements DIFace {
...
```
e.g. `@Json` (for the concrete type) + `@Json.Import` (for the interface + implementation)
```java
@Json.Import(value = DIFace.class, implementation = MyDIFace.class)
@Json
public record MyDIFace(String one, long two) implements DIFace {
...
```
=> Add support for Interface type fromJson() by specifying an implementation

blackbox-test/src/test/java/org/example/other/ObjectAdapterTest.java, jsonb/src/main/java/io/avaje/jsonb/stream/JParser.java
This fix moves the currentToken() if nothing has been read yet, which is the case when using jsonb.type(Object.class) reading unknown nullable types
=> Fix for jsonb.type(Object.class).fromJson(...)

README.md
Use consistent naming in examples.
=> Fix annotation processor property example in README

.github/workflows/build.yml, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java, jsonb/pom.xml, jsonb/src/main/java/io/avaje/jsonb/Json.java, jsonb/src/main/java/io/avaje/jsonb/stream/JsonOutput.java, jsonb/src/main/java/io/avaje/jsonb/stream/NimaJsonOutput.java, jsonb/src/main/java/module-info.java
[M2 Released](https://github.com/helidon-io/helidon/releases/tag/4.0.0-M2)
=> Helidon 4.0-M2

blackbox-test/src/main/java/org/example/customer/ctor/MyMessage.java, jsonb-generator/pom.xml, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
This case comes about with the way Jackson wants
to have a default constructor, so it looks a little
odd but good to support.
e.g.
```java
@Json
public class MyMessage {
protected String path;
protected String field;
protected String message;
public MyMessage(String path, String field, String message) {
this.path = path;
this.field = field;
this.message = message;
}
/** Default constructor typically to help Jackson onlu. */
public MyMessage() {
}
public String getPath() {
return path;
}
public String getField() {
return field;
}
public String getMessage() {
return message;
}
}
```
=> Handle case of default constructor that we don't use 

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java
Should read `io.avaje.jsonb.plugin` instead of `.json.plugin`.
=> Fix typo in ProcessingContext

blackbox-test/pom.xml, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/ProcessorTest.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/MyThrowable.java
it seems that on JDK 21 there are some slight differences that caused generation to fail.
- adjust generator tests to compile with the current release flag
- fix throwable generation to ensure no from Json is generated
=> Fix Throwable Generation

jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/TestClass.java, jsonb/src/main/java/io/avaje/jsonb/Json.java
=> Support `@Json.Property` Methods

blackbox-test/src/test/java/org/example/customer/BasicPubFieldsTest.java, jsonb-jackson/src/main/java/io/avaje/jsonb/jackson/JacksonReader.java, jsonb-jackson/src/main/java/io/avaje/jsonb/jackson/JacksonWriter.java, jsonb-jackson/src/test/java/io/avaje/jsonb/jackson/UnwrapJacksonParserTest.java, jsonb/src/main/java/io/avaje/jsonb/JsonReader.java, jsonb/src/main/java/io/avaje/jsonb/JsonWriter.java, jsonb/src/main/java/io/avaje/jsonb/core/ObjectJsonReader.java, jsonb/src/main/java/io/avaje/jsonb/spi/DelegateJsonWriter.java, jsonb/src/main/java/io/avaje/jsonb/stream/JsonReadAdapter.java, jsonb/src/main/java/io/avaje/jsonb/stream/JsonWriteAdapter.java
=> Add JsonReader.unwrap() to access underlying JsonParser when using avaje-jsonb-jackson

jsonb/src/main/java/io/avaje/jsonb/core/BasicTypeAdapters.java
Currently, unknown Number Types are serialized to double, which may cause issues for those expecting a non-decimal number.
=> Upgrade `ObjectAdapter` to deserialize to long in certain situations

blackbox-test/src/main/java/org/example/customer/creator/PropertyCreator.java, blackbox-test/src/test/java/org/example/customer/creator/PropertyCreatorTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Processor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/PropertyCreator.java, jsonb/src/main/java/io/avaje/jsonb/core/JavaTimeAdapters.java
It seems that when using `Json.Property` on a field and also `Json.Creator` the code generates incorrectly
=> Fix `Json.Creator` Interaction with `Json.Property`

jsonb/src/main/java/io/avaje/jsonb/CustomAdapter.java, jsonb/src/main/java/io/avaje/jsonb/Json.java
I can't think of a reason to have `Class` retention
=> Make Annotations `SOURCE` retention

jsonb-generator/src/main/java/io/avaje/jsonb/generator/AdapterName.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/JsonbProcessor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
- fix mixins stopping multi imports
- fix adapter generation to have all enclosingTypes in the name
- adds validation to mixins such that access modifers must match the target class
=> Fix Mixins/AdapterName Generation

blackbox-test/pom.xml, jsonb-generator/pom.xml, jsonb-generator/src/main/java/io/avaje/jsonb/generator/JsonbProcessor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ProcessingContext.java, pom.xml
Currently, the only way for annotation processors to directly communicate with each other and maven plugins is by writing files and reading them.
Using `Elements` or `Class.forName` to detect other running processors is also unreliable.
This PR enhances the generator to write a marker in `target/avaje-processors.txt` that other processors and tools can pick up.
relies on https://github.com/avaje/avaje-prisms/pull/69
=> Writes a file to signal the generator's presence

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/PropertyCreator.java
Fixes issue where `Json.Creator` variable names generated incorrect code when used in combination with `Json.Property`
=> Fix Creator Generation Error

jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleAdapterWriter.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/SimpleComponentWriter.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/Util.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ValueReader.java
- Will write value classes when on Valhalla
- modify @Json.Value generation for compatibility (apparently you can't use `return` in a value class constructor)
resolves #281
=> Write value classes when running on Valhalla

blackbox-test/src/main/java/org/example/customer/inetaddress/MyInetAddress.java, blackbox-test/src/test/java/org/example/customer/inetaddress/MyInetAddressTest.java, jsonb/src/main/java/io/avaje/jsonb/core/BasicTypeAdapters.java
Perhaps adding a usage for valid IPv4 and IPv6 serialization/de-serialization, in blackbox-test, would be desired.
=> Add InetAddressAdapter for serialization of all InetAddress variations

jsonb-generator/src/main/java/io/avaje/jsonb/generator/Constants.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/JsonbProcessor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/package-info.java, jsonb/src/main/java/io/avaje/jsonb/Json.java
When using JDK 23+ module imports, the `List` type from `java.base`  and `io.avaje.jsonb` have a name collision.
```java
import module java.base;
import module io.avaje.jsonb;
public class Example {
void main() {
List.of(); // this fails to resolve the import
}
}
```
=> Fix Repeatable Annotation Name Collision

json-node/.editorconfig, json-node/pom.xml, json-node/src/main/java/io/avaje/json/node/JsonArray.java, json-node/src/main/java/io/avaje/json/node/JsonNode.java, json-node/src/main/java/io/avaje/json/node/JsonObject.java, json-node/src/main/java/module-info.java, json-node/src/test/java/io/avaje/json/node/JsonArrayTest.java, json-node/src/test/java/io/avaje/json/node/JsonObjectTest.java
```java
JsonArray phoneNumbers = ...;
List<String> result =
phoneNumbers.stream()
.filter(n -> "home".equals(n.extract("type")))
.map(n -> n.extract("number"))
.collect(Collectors.toList());
```
extract() can take a dot notation path like `person.name` (so not JSONPath)
```java
var node = JsonObject.create()
.add("person", JsonObject.create().add("name", "myName").add("type", "doo").add("active", true))
.add("address", JsonObject.create().add("size", 42).add("junk", 99L).add("other", JsonObject.create().add("deep", "one")));
JsonNode name = node.find("name");
assertThat(name).isNull();
JsonNode personName = node.find("person.name");
assertThat(personName).isNotNull();
assertThat(personName.text()).isEqualTo("myName");
assertThat(node.extract("person.name")).isEqualTo("myName"); …
```
=> [json-node] Add extract() methods to assist filtering and mapping

json-node/src/main/java/io/avaje/json/node/JsonArray.java, json-node/src/main/java/io/avaje/json/node/JsonBoolean.java, json-node/src/main/java/io/avaje/json/node/JsonDecimal.java, json-node/src/main/java/io/avaje/json/node/JsonDouble.java, json-node/src/main/java/io/avaje/json/node/JsonInteger.java, json-node/src/main/java/io/avaje/json/node/JsonLong.java, json-node/src/main/java/io/avaje/json/node/JsonNode.java, json-node/src/main/java/io/avaje/json/node/JsonObject.java, json-node/src/main/java/io/avaje/json/node/JsonString.java, json-node/src/test/java/io/avaje/json/node/JsonArrayTest.java, json-node/src/test/java/io/avaje/json/node/JsonObjectTest.java
Ability to create a mutable deep copy and an immutable deep copy
=> [json-node] Add copy() and unmodifible() for deep copy options

json-node/src/main/java/io/avaje/json/node/JsonArray.java, json-node/src/main/java/io/avaje/json/node/JsonNode.java, json-node/src/main/java/io/avaje/json/node/JsonObject.java, json-node/src/test/java/io/avaje/json/node/ExtractNodeTest.java
Example `.extractNode("person")`
```java
JsonArray arrayWithNestedPerson = (JsonArray) object.get("people");
List<JsonNode> peopleNodes =
arrayWithNestedPerson.stream()
.filter(node -> "family".equals(node.extract("type")))
.map(node -> node.extractNode("person")). // <!-- HERE ... .extractNode("person")
.collect(Collectors.toList());
```
=> [json-node] Add extractNode() and empty() helpers for JsonArray and JsonObject

blackbox-test/pom.xml, blackbox-test/src/test/java/org/example/other/JsonNodeAdaptersTest.java, json-node/pom.xml, json-node/src/main/java/io/avaje/json/node/adapter/JsonNodeComponent.java, json-node/src/main/java/module-info.java, json-node/src/main/resources/META-INF/services/io.avaje.jsonb.spi.JsonbExtension, jsonb/pom.xml
That is, we need to explicitly include avaje-json-node in the classpath/module path.
When JsonB starts with avaje-json-node present, it will register with JsonB thus support the JsonNode types in JsonB.
=> [json-node] Make avaje-json-node an optional component for JsonB

json-core/src/main/java/module-info.java, json-node/src/main/java/io/avaje/json/node/JsonNodeMapper.java, json-node/src/main/java/io/avaje/json/node/NodeMapper.java, json-node/src/main/java/io/avaje/json/node/adapter/DJsonNodeMapper.java, json-node/src/main/java/io/avaje/json/node/adapter/DMapper.java, json-node/src/main/java/io/avaje/json/node/adapter/JsonNodeComponent.java, json-node/src/main/java/io/avaje/json/node/adapter/NodeAdapter.java, json-node/src/main/java/io/avaje/json/node/adapter/NodeAdapterBuilder.java, json-node/src/test/java/io/avaje/json/node/ExtractNodeTest.java, json-node/src/test/java/io/avaje/json/node/JsonArrayTest.java, json-node/src/test/java/io/avaje/json/node/NodeMapperTest.java, json-node/src/test/java/io/avaje/json/node/adapter/JsonNodeAdaptersTest.java
Although this provides all the JsonAdapters for the JsonNode types, for developers using it directly they will view it more like a "mapper" with convenience methods for toJson() and fromJson()
=> [json-node] Rename JsonNodeAdapter to JsonNodeMapper

json-core/src/main/java/io/avaje/json/core/BasicObjectAdapter.java, json-core/src/main/java/io/avaje/json/core/CoreTypes.java, json-core/src/main/java/io/avaje/json/simple/DSimpleMapper.java, json-core/src/main/java/io/avaje/json/simple/DSimpleMapperBuilder.java, json-core/src/main/java/io/avaje/json/simple/DTypeMapper.java, json-core/src/main/java/io/avaje/json/simple/SimpleMapper.java, json-core/src/main/java/module-info.java, json-core/src/test/java/io/avaje/json/core/CoreTypesTest.java, json-core/src/test/java/io/avaje/json/simple/SimpleMapperTest.java
```java
static final SimpleMapper simpleMapper = SimpleMapper.builder().build();
void test() {
Map<String, Long> map = new LinkedHashMap<>();
map.put("one", 45L);
map.put("two", 93L);
String asJson = simpleMapper.toJson(map);
assertThat(asJson).isEqualTo("{\"one\":45,\"two\":93}");
Map<String, Object> mapFromJson = simpleMapper.fromJsonObject(asJson);
assertThat(mapFromJson).containsKeys("one", "two");
assertThat(mapFromJson.toString()).isEqualTo("{one=45, two=93}");
}
```
=> [json-core] Add SimpleMapper API to core to make it easier for reading/writing simple Maps, Lists etc

json-core/src/main/java/io/avaje/json/simple/DSimpleMapper.java, json-core/src/main/java/io/avaje/json/simple/SimpleMapper.java, json-core/src/test/java/io/avaje/json/simple/CustomAdapter2Test.java, json-core/src/test/java/io/avaje/json/simple/CustomAdapterTest.java
For cases where we want to manually build a JsonAdapter and then use that via SimpleMapper
=> [json-core] SimpleMapper add type support for customer JsonAdapters

json-node/src/main/java/io/avaje/json/node/JsonNode.java, json-node/src/main/java/io/avaje/json/node/JsonNodeMapper.java, json-node/src/main/java/io/avaje/json/node/JsonObject.java, json-node/src/main/java/io/avaje/json/node/NodeMapper.java, json-node/src/main/java/io/avaje/json/node/adapter/DJsonNodeMapper.java, json-node/src/main/java/io/avaje/json/node/adapter/DMapper.java, json-node/src/test/java/io/avaje/json/node/CustomAdapterTest.java
For cases where we want to manually build a JsonAdapter and then use that via JsonNodeMapper.
For example, manually build JsonAdapter using JsonObject.extract() methods to extract out values and deal with number types etc.
=> [json-node] JsonNodeMapper add type support for customer JsonAdapters

json-core/pom.xml, json-node/pom.xml, jsonb/pom.xml
I think avaje-json is too close to avaje-jsonb (like typo close) and so I think it would be better for core to be avaje-json-core.
=> [json-core] Rename the Maven ArtifactId to avaje-json-core

json-core/src/main/java/io/avaje/json/simple/DSimpleMapper.java, json-core/src/main/java/io/avaje/json/simple/SimpleMapper.java, json-core/src/test/java/io/avaje/json/simple/CustomAdapter2Test.java
Make this performance optimisation available via SimpleMapper. The PropertyNames are pre-encoded, and can give a performance boost in both writing and reading.
=> [json-core] Add SimpleMapper.properties() method, option to use PropertyNames optimisation

json-core/src/main/java/io/avaje/json/simple/SimpleMapper.java, json-core/src/test/java/io/avaje/json/simple/CustomAdapterTest.java, json-node/src/main/java/io/avaje/json/node/JsonNodeMapper.java, json-node/src/main/java/io/avaje/json/node/adapter/DJsonNodeMapper.java, json-node/src/test/java/io/avaje/json/node/CustomAdapterTest.java
Match the feature of SimpleMapper and Jsonb.
=> [json-node] Add JsonNodeMapper.properties() method

json-node/src/main/java/io/avaje/json/node/JsonNode.java, json-node/src/main/java/io/avaje/json/node/JsonObject.java, json-node/src/main/java/io/avaje/json/node/adapter/DecimalAdapter.java, json-node/src/main/java/io/avaje/json/node/adapter/NodeAdapter.java, json-node/src/test/java/io/avaje/json/node/ExtractNodeTest.java, json-node/src/test/java/io/avaje/json/node/JsonObjectTest.java, json-node/src/test/java/io/avaje/json/node/adapter/JsonNodeAdaptersTest.java
=> [json-node] Fix NULL value bug with JsonObject

json-core/src/main/java/io/avaje/json/simple/DSimpleMapper.java, json-core/src/main/java/io/avaje/json/simple/SimpleMapper.java, json-core/src/test/java/io/avaje/json/simple/SimpleMapperTest.java, json-node/src/main/java/io/avaje/json/node/JsonNodeMapper.java, json-node/src/main/java/io/avaje/json/node/adapter/DJsonNodeMapper.java, json-node/src/test/java/io/avaje/json/node/adapter/JsonNodeAdaptersTest.java
This makes it more trivially obvious when using SimpleMapper or JsonNodeMapper to implement a JsonAdapter [where the API uses JsonReader and JsonWriter]
=> [json-core] Add helper toJson() fromJson() methods that use JsonReader JsonWriter

json-core/src/main/java/io/avaje/json/simple/DExtract.java, json-core/src/main/java/io/avaje/json/simple/JsonExtract.java, json-core/src/main/java/io/avaje/json/simple/SimpleMapper.java, json-core/src/test/java/io/avaje/json/simple/SimpleMapperTest.java
Helps mostly when extracting values out of nested documents, and dealing with the various number types and type conversion
Example:
```java
String json = "{\"name\":\"Rob\",\"score\":4.5,\"whenActive\":\"2025-10-20\",\"address\":{\"street\":\"Pall Mall\"}}";
Map<String, Object> mapFromJson = simpleMapper.fromJsonObject(json);
JsonExtract extract = simpleMapper.extract(mapFromJson);
String name = extract.extract("name");
double score = extract.extract("score", -1D);
String street = extract.extract("address.street");
LocalDate activeDate = extract.extractOrEmpty("whenActive")
.map(LocalDate::parse)
.orElseThrow();
```
=> [json-core] Add JsonExtract helper to ease extracting values and number types from raw Map<String,Object>

blackbox-test/src/test/java/org/example/customer/CustomerTest.java, json-core/src/main/java/io/avaje/json/stream/JsonOutput.java, json-core/src/main/java/io/avaje/json/stream/core/CoreJsonStream.java, jsonb/src/main/java/io/avaje/jsonb/Jsonb.java, jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java
This method is on JsonType but was missing on Jsonb itself.
Also deprecate JsonOutput.of() taking an OutputStream in favour of JsonOutput.ofStream() in order to skip method overloading on the option helidon server response type.
=> Add Jsonb.toJson() using JsonOutput

blackbox-test/src/main/java/org/example/customer/naming/PropertyUnderscore.java, blackbox-test/src/test/java/org/example/customer/naming/PropertyUnderscoreTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/naming/PropertyUnderscore.java
Now will read the getter/setter methods using the property name if no match if found for the field name.
This was prompted by
=> [bug] @Json.Property name not used to match getters/setters/constructors using property name

blackbox-test/src/main/java/org/example/customer/jaxb/MyJaxbType.java, blackbox-test/src/test/java/org/example/customer/jaxb/MyJaxbTypeTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldProperty.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
Instead they have getter methods that initialise the collection like:
```java
public List<String> getTags() {
if (tags == null) {
tags = new ArrayList<>();
}
return tags;
}
```
This change detects the case when a field does not have any matching constructor or setter, and it's a collection type (List,Set,Collection), then we assume it follows JAX-B style and the getter will initialise the collection.
We then generate code that uses the getter + addAll() ... instead of failing with the error:
"Non public field org.example.MyJaxbType tags with no matching setter or constructor?"
=> Add support for JAX-B style collections that don't have setters

blackbox-test/src/main/java/org/example/customer/package-info.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/JsonbProcessor.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
Improve the compiler error to more clearly indicate the source of the error. Add the Json.Import and Json.Mixin prefix if they are the original source of the error.
Instead of:
```
[ERROR] Non public field java.util.Calendar fields with no matching setter or constructor?
```
Produce:
```
[ERROR] @Json.Import of java.util.Calendar, non public field fields with no matching setter or constructor?
```
=> Improve the compiler error with Json.Import / Json.Mixin prefix

jsonb-generator/src/main/java/io/avaje/jsonb/generator/AdapterName.java
- It turns out using toString on a package element doesn't print the right package name with some compilers
- Records with `@Property` annotations on record components did not generate correctly with JDT
=> Fix JDT package errors 

jsonb-generator/src/main/java/io/avaje/jsonb/generator/TypeReader.java
Fixes error where records generate incorrectly on JDT
=> Fix JDT `@Property` records

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldReader.java
Instead of generating code like:
```java
MyType myType = new MyType(...);
return myType;
```
Generate:
```java
return new MyType(...);
```
=> Generated code with "direct return" when no setters required

blackbox-test/src/test/java/org/example/customer/jaxb/MyJaxbTypeTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldProperty.java, jsonb/src/main/java/io/avaje/jsonb/Types.java
The JAXB collections don't have setters but instead lazy initialise collections on getter methods, the generated code uses <getter>.addAll() which doesn't support the case when NULL is returned (vs empty collection).
Fix is to add a nullToEmpty() helper method for this case (JAXB style collections).
Fix to generated code adds the `Types.nullToEmpty()` like:
```java
case "tags": 
_$myJaxbType.getTags().addAll(Types.nullToEmpty(listStringJsonAdapter.fromJson(reader)));
break;
```
=> Fix JAXB collections deserializing null

blackbox-test/src/main/java/org/example/other/custom/serializer/CustomExample2.java, blackbox-test/src/main/java/org/example/other/custom/serializer/MoneySerializer2.java, blackbox-test/src/test/java/org/example/other/custom/serializer/SelectiveCustomSerializerSupplierTest.java, blackbox-test/src/test/java/org/example/other/custom/serializer/SelectiveCustomSerializerTest.java, jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java
Fix in DJsonb by adding `.nullSafe()` for the `Supplier<JsonAdapter<T>>` case.
Example:
```java
@CustomAdapter(global = false)
public class MoneySerializer2 implements JsonAdapter<BigDecimal> {
/**  Default constructor -> registered via {@code Supplier<JsonAdapter>} */
public MoneySerializer2() { }
@Override
public BigDecimal fromJson(JsonReader reader) {
return reader.readDecimal().setScale(2, RoundingMode.DOWN);
}
@Override
public void toJson(JsonWriter writer, BigDecimal value) {
writer.value(value.setScale(2, RoundingMode.DOWN));
}
}
```
Due to using the default constructor, this custom JsonAdapter is registered via `Supplier<JsonAdapter<T>>` and that wasn't getting the `.nullSafe()` wrapper.
=> Fix NPE when custom JsonAdapter (not nullSafe()) is registered via Supplier

json-core/src/main/java/io/avaje/json/core/CollectionAdapter.java, json-core/src/main/java/io/avaje/json/core/MapAdapter.java, json-core/src/test/java/io/avaje/json/core/CoreTypesTest.java
It seems passing a null map/list for serialization throws an NPE
=> Collection adapter nullsafety

blackbox-test/src/main/java/org/example/other/MyPrimitives.java, blackbox-test/src/test/java/org/example/FailOnNullPrimitivesTest.java, json-core/src/main/java/io/avaje/json/stream/JsonStream.java, json-core/src/main/java/io/avaje/json/stream/core/CoreJsonStream.java, json-core/src/main/java/io/avaje/json/stream/core/JParser.java, json-core/src/main/java/io/avaje/json/stream/core/JsonReadAdapter.java, json-core/src/main/java/io/avaje/json/stream/core/JsonStreamBuilder.java, json-core/src/test/java/io/avaje/json/mapper/PrimitivesTest.java, json-core/src/test/java/io/avaje/json/stream/core/JsonReadAdapterTest.java, jsonb-spring-adapter/src/main/java/io/avaje/jsonb/spring/JsonbAutoConfiguration.java, jsonb/src/main/java/io/avaje/jsonb/Jsonb.java, jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java
- Default to allowing NULL for primitives like Jackson
- Add failOnNullPrimitives=true configuration option
=> Add failOnNullPrimitives option, default to allowing NULL

jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java, jsonb/src/test/java/io/avaje/jsonb/core/TestBuilder.java
I can't see a reason to return separate instances.
Essentially this change causes the same `Jsonb` instance to be returned by the statement `Jsonb.builder().build()`
=> return default instance on unchanged builder

blackbox-test/src/main/java/org/example/customer/properties/Props.java, blackbox-test/src/test/java/org/example/customer/properties/PropsTest.java, jsonb/src/main/java/io/avaje/jsonb/core/BasicTypeAdapters.java
Got a request from the Discord to add it
=> Add properties json adapter

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ComponentReader.java
It should not be conditional on MetaData, as most often MetaData will be present and it was incorrectly not adding the factories
=> Fix ComponentReader to register MetaData.Factory if present

blackbox-test/src/test/java/org/example/customer/stream/StreamBasicTest.java, jsonb/src/main/java/io/avaje/jsonb/core/StreamAdapter.java
When the stream is empty, we still need to send some response body when used with an http server.
The fix for this is to always append a blank empty line to the content. Client consumers are expected to ignore empty content (filter empty lines).
=> Fix JsonType.streamAsLines() for empty Stream

json-core/src/main/java/io/avaje/json/stream/core/JGenerator.java, json-core/src/test/java/io/avaje/json/stream/core/JsonWriterTest.java
Currently, the underlying buffer will expand when writing raw String content that is larger that the buffer. This change writes that as chunks instead.
=> Support writing large raw String content without expanding the underlying buffer

json-core/src/main/java/io/avaje/json/JsonWriter.java, json-core/src/main/java/io/avaje/json/stream/DelegateJsonWriter.java, json-core/src/main/java/io/avaje/json/stream/core/JGenerator.java, json-core/src/main/java/io/avaje/json/stream/core/JsonGenerator.java, json-core/src/main/java/io/avaje/json/stream/core/JsonWriteAdapter.java, json-core/src/test/java/io/avaje/json/stream/core/JsonWriterTest.java, jsonb-jackson/src/main/java/io/avaje/jsonb/jackson/JacksonWriter.java
I've hit an interesting use case where a single json value is a really large amount of content. Instead of writing this content as a really big string, support writing it as multiple small raw chunks.
Note that this feature isn't supported using the Jackson core JsonGenerator.
=> Support writing large raw json content in multiple chunks

json-core/pom.xml, json-node/pom.xml, jsonb-generator/pom.xml, jsonb-inject-plugin/pom.xml, jsonb-jackson/pom.xml, jsonb-spring-adapter/pom.xml, jsonb/pom.xml
Having the license information in the POM file allows it to be self-contained. A glance to it is enough to determine licensing.
This is especially important for private artifact mirrors, that often do not allow closed-source, source-available or hard-copyleft libraries to be used. Without the license information on the POM file, some of these repositories will deny mirroring this library.
I'm trying to mirror the Avaje libraries in a private artifact repository, but am running into the issue of the repository not being able to extract the license from the repository (likely not a part of the JARs), which then means that it doesn't mirror the libraries correctly.
=> Add explicit license information to packages' POM file

jsonb/src/main/java/io/avaje/jsonb/Jsonb.java, jsonb/src/main/java/io/avaje/jsonb/core/CoreAdapterBuilder.java, jsonb/src/main/java/io/avaje/jsonb/core/DJsonb.java, jsonb/src/test/java/io/avaje/jsonb/core/HasAdapterTest.java
I took a crack at #414. 
I'm not sure if you think that this `hasAdapter` method should populate the cache. My thinking was that if you were doing this lookup, you'd want to get the adapter soon after. This avoid raising the exception and populating the stack trace and lookup stack if using `hasAdapter`.
=> Add a hasAdapter method to the JsonB interface

blackbox-test/src/main/java/org/example/customer/generics/MyListWrapperRecord.java, blackbox-test/src/test/java/org/example/customer/generics/MyListWrapperRecordTest.java, jsonb-generator/src/main/java/io/avaje/jsonb/generator/FieldProperty.java
=> Fix record nested generics

jsonb-generator/src/main/java/io/avaje/jsonb/generator/ClassReader.java, jsonb-generator/src/test/java/io/avaje/jsonb/generator/models/valid/naming/PackageNaming.java
If you happened to name a class `Package` or some other restricted java keyword, a compilation error would happen
=> Fix Invalid `toJson` parameter name
